modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/Lykrast/Turf/issues"

[[mods]]
modId="turf"
version="${version}"
displayName="Turf"
displayURL="CHANGEIT"
credits="Quark for inspiration"
authors="Lykrast"
description='''
Turf blocks which are non decaying grass on all sides, for decoration. Can be dyed and made into stairs and stuff.
'''

[[dependencies.turf]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.turf]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"