modLoader="javafml"
loaderVersion="[41,)"
issueTrackerURL="https://github.com/Lykrast/Turf/issues"
license="MIT License https://github.com/Lykrast/Turf/blob/master/LICENSE"

[[mods]]
modId="turf"
version="${file.jarVersion}"
displayName="Turf"
displayURL="https://www.curseforge.com/minecraft/mc-mods/turf"
credits="Quark for inspiration, DarkCow for the idea of dying them"
authors="Lykrast"
description='''
Turf blocks which are non decaying grass on all sides, for decoration. Can be dyed and made into stairs, slabs and walls.
'''

[[dependencies.turf]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.turf]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,]"
    ordering="NONE"
    side="BOTH"